name: movie
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: {sdk: '>=3.0.5 <4.0.0'}
dependencies:
  flutter: {sdk: flutter}
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dio: ^5.2.1+1
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  google_fonts: 4.0.4
  animate_do: ^2.1.0
  carousel_slider: ^4.1.1
  cached_network_image: ^3.0.1
  shimmer: ^2.0.0
dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets: []
  fonts: []
